### ISSUE TITLE
iConomyChestShop conflicts with BlockLocker - players can steal items

### ISSUE THREAD

**Issue by Jake4-CX** [rutgerkok/BlockLocker#103]
One of my players on my server has just figured out a way on how to get around BlockLockers protection. This **is** caused by a third party plugin, but it is a very popular plugin for Survival servers (iConomyChestShop - 5.4m downloads). 

This works by a player (who isn't the chest owner) places a sign on the protected chest and creates a ChestShop for this specific chest, this then gives the player full access to this protected chest and denies the original chest owner from accessing the chest.

**Comment by rutgerkok** [comment]
This isn't a bug in BlockLocker, this is something that needs to be fixed in iConomyChestShop.

I went ahead and fixed it in iConomyChestShop myself. I've submitted my code in https://github.com/ChestShop-authors/ChestShop-3/pull/414 . If you want to test this as a JAR file, you can download it here:

[ChestShop.zip](https://github.com/rutgerkok/BlockLocker/files/6057349/ChestShop.zip)

**Comment by Jake4-CX** [comment]
Thanks for releasing the fix, I've been using BlockLocker for the past few months and it worked flawlessly. 👌
