### ISSUE TITLE
Disable bungeecord checker

### ISSUE THREAD

**Issue by eUipKh** [rutgerkok/BlockLocker#105]
Can you make a config option to disable this checker?

https://github.com/rutgerkok/BlockLocker/blob/master/src/main/java/nl/rutgerkok/blocklocker/impl/converter/UUIDHandler.java#L359

It would be really helpful for us

**Comment by rutgerkok** [comment]
In principle I can, but how would it help you?

**Comment by eUipKh** [comment]
We have an offline-mode network, this part of the code ignores that and put BlockLocker in online-mode

**Comment by rutgerkok** [comment]
Ok, I'm going to deny this feature request. BlockLocker has limited support for offline mode, so that you can still use it with your friends on a server not connected to the internet. But to spend time to add an option so that large servers can pirate the game - I'm not going to do that.

(I realize that the sale price of Minecraft doesn't always scale with the economy of a country. But still I'm not going to spend time to support piracy.)

**Comment by eUipKh** [comment]
Good thing this is open source, thanks anyway.
