### ISSUE TITLE
~ character appearing in all my players protections

### ISSUE THREAD

**Issue by chistian95** [rutgerkok/BlockLocker#112]
So I've updated the plugin to the latest version and now a lot of my players are getting a '~' in front of their name everytime they open a chest or a door. I'm having to manually remove every protection because it gets broken again and again and again. 

I've read in the spigot forums that this has something to do with offline UUIDs or something like that. I would like a way to bypass this thing because it literally makes the plugin unusable in my case...

**Comment by rutgerkok** [comment]
The latest version (1.10) uses a new way of storing UUIDs on the signs. So all old signs are converted to the new saving format. In that process, any missing UUIDs are fetched. If such an UUID cannot be found (the player is offline and account.mojang.com returns no result), the name is deemed invalid and a ~ is added.

The plugin should automatically fall back to using names when your server is running in offline mode. However, when it's running behind a Bungee proxy, the plugin will still use UUIDs, as it will assume that the proxy handles the Mojang authentication. So that means that pirated Bungee networks are out of luck. See also #105.

**Comment by chistian95** [comment]
Good thing this is open source, thanks anyway.
