### ISSUE TITLE
Double doors can have their protection bypassed by normal players

### ISSUE THREAD

**Issue by baailey** [rutgerkok/BlockLocker#114]
Plugin version: 1.10
Server version: git-Tuinity-"2310a94" (MC: 1.17.1)

As shown in [this screenshot](https://i.imgur.com/ZUqWnHZ.png) there are 2 different ways people may set up double doors. 

The issue is the double door on the left. If the doors are facing ONLY to the right, then the door on the right will not be included in the sign protection unless the sign is placed on either of the doors. If it is placed above/below, then the one on the right will not be included in the protection and anyone can access them

Surprisingly, if both doors are facing to the left it works fine.

**Comment by rutgerkok** [comment]
Thanks for reporting. The double door on the left is not really a double door, so it should function as two single doors.

I've now changed the plugin so that it properly checks the facing and hinge of the other door, so this issue should be resolved.

Build 39+ will contain this fix. ( https://ci.codemc.io/job/rutgerkok/job/BlockLocker/ ) I'll push the update to Spigotmc.org tomorrow, assuming no issues are found.

**Comment by baailey** [comment]
Awesome thank you
