### ISSUE TITLE
Locking Doors that are near a chest block

### ISSUE THREAD

**Issue by Skizzles** [rutgerkok/BlockLocker#124]
![image](https://user-images.githubusercontent.com/30563757/143957938-fb6c07b2-7d14-4a1d-afda-1ae326c4841d.png)
By this image the sign is locking the door that is behind the chest as well as the chest.

Config:
https://paste.skizzles.me/unimesuroj.yaml

**Comment by rutgerkok** [comment]
Sorry for the late reply, I missed this.

Amusingly, this works for any block, not just a chest. A dirt block would also work. It's just that BlockLocker prevents you from placing a protection sign on a dirt block, you'd need something like WorldEdit. (Or a protectable block, as you have shown.)

Because I don't want to invalidate these protections, I've decided to just make it work for all block types. So you can now attach a sign to any block next to a door, and it'll work.

If you want to test this, the latest dev build can be found here: https://ci.codemc.io/job/rutgerkok/job/BlockLocker/ . The code change (commit) can be found here: https://github.com/rutgerkok/BlockLocker/commit/fab7c93065d7b10be6383b238057628fec0e5ed9 .
