### ISSUE TITLE
Hope compatible 1.20 this plugin

### ISSUE THREAD

**Issue by LoveXiaoMan** [rutgerkok/BlockLocker#161]
Hope compatible 1.20 this plugin

**Comment by CleMooling** [comment]
Well this plugins has adapted MC1.20 automatically, but there is a problem that if you stick a sign on a block, the plugin will think the block as a container and try to protect it whether the block is a container or not. A temporary solution is sneak to stick the sign, but I hope author of this plugin can help solve it.

**Comment by CleMooling** [comment]
@rutgerkok I think you should close issues about game versions update before the fixed plugin version released, because it's really hard to get the dev builds for a common user, and before this the problem can't be solved really.

**Comment by rutgerkok** [comment]
Yeah, ideally Github would show "Fixed in next release" instead of "Closed". The thing is, Github automatically closes the issue once I make a commit message that contains the text "Fixes #161".

Anyways, the release is now uploaded to Github, at https://github.com/rutgerkok/BlockLocker/releases/tag/v1.12.1 . It should appear on Spigot soon.

**Comment by CleMooling** [comment]
> Yeah, ideally Github would show "Fixed in next release" instead of "Closed". The thing is, Github automatically closes the issue once I make a commit message that contains the text "Fixes #161".
> 
> Anyways, the release is now uploaded to Github, at https://github.com/rutgerkok/BlockLocker/releases/tag/v1.12.1 . It should appear on Spigot soon.

Fine, thanks for your help.
