### ISSUE TITLE
Plugin works in wrong place

### ISSUE THREAD

**Issue by CleMooling** [rutgerkok/BlockLocker#162]
If you stick a sign on a block, the plugin will think the block as a container and try to protect it whether the block is a container or not. A temporary solution is sneak to stick the sign, but I hope author of this plugin can help solve it. I referred to it in issue #161, and today I tried the new version in my server, this problem is still exist.
And the sign on a container can be edited properly as the update tips.
I'm using Leaves, which can be searched in GitHub and developed by LeavesMC, is a downstream branch of Paper. The server is latest.
Plugin version: v1.12.1

**Comment by rutgerkok** [comment]
Can't reproduce this. If I place a sign on a random wall, I can just place an empty sign as usual. If I then add [Private] to line 1, the sign pops off as expected, and BlockLocker gives an error about there not being a protection there.

I'm using Paper on Minecraft 1.20, with BlockLocker 1.12.1.

Could you help me narrowing down this issue? Could you test this on a server without other plugins on Paper with the default BlockLocker config, and then check what makes the issue reappear? Then I now where the issue is.

**Comment by CleMooling** [comment]
I tested it just now, and the problem disappeared, maybe I got something wrong.

**Comment by CleMooling** [comment]
I tested it just now, and the problem disappeared, maybe I got something wrong.
