### ISSUE TITLE
dont working to me

### ISSUE THREAD

**Issue by Tolmwn** [rutgerkok/BlockLocker#166]
Hey guys ! I want to ask why the plugin its not working to me ! I already put it at the plugin folder with the rest from my plugins but its not working! I have already do restart the server but the plugin its still not work and its not giving me any folder with the files from the plugin. I need dowloand any other plugin together to work ? Thanks you :D

**Comment by rutgerkok** [comment]
Do you have the correct version? Not every version works on every Minecraft version. See the overview on this page: https://github.com/rutgerkok/BlockLocker/releases

Otherwise I can't really say anything, except that it's working fine on my side. If you need more help, you'll need to post the console output at startup, then I can check whether there's anything in there.

**Comment by Tolmwn** [comment]
so its not working at the version 1.19.4 ? Its only for 1.20 ?

**Comment by rutgerkok** [comment]
For 1.19.4, you need to download this version:

https://github.com/rutgerkok/BlockLocker/releases/tag/v1.12
