### ISSUE TITLE
1.13.2+ support

### ISSUE THREAD

**Issue by LogGits** [rutgerkok/BlockLocker#27]
Hey I have been advised by many people over at paper and spigot to not update to 1.14+ until a completely stable minecraft version is released. Would you be able to make the plugin support 1.13.2 aswell?

**Comment by rutgerkok** [comment]
No, but you can download an older version of the plugin: https://github.com/rutgerkok/BlockLocker/releases/tag/v1.5.0

The reason I'm doing this is because I don't want to spend too much time maintaining this plugin. Of course, I could write the code such that it supports both the old SIGN and WALL_SIGN and the six new signs, but that would take quite a bit of time, and it would also lead to some hacky Java code. Besides, this plugin doens't really receive new features, so the only change between BlockLocker 1.5 and the current version are changes related to Minecraft 1.14.
