### ISSUE TITLE
More Users does not work

### ISSUE THREAD

**Issue by Manu5656** [rutgerkok/BlockLocker#40]
If a user writes [More Users] on a container and the name of another user does not work, the user who was cited cannot open that container. I'm using the latest version of the plugin on a 1.14.4 server

**Comment by rutgerkok** [comment]
Works fine for me, I can still open this chest:

![2019-12-08_10 32 38](https://user-images.githubusercontent.com/1462188/70387564-c9418000-19a6-11ea-8db7-e5a8c427061b.png)

* If your server allows cracked accounts, then BlockLocker will not work correctly.
* If your server is not in English, take a look in the `plugins/BlockLocker` folder to see how `[More Users]` was translated.
* Otherwise, it's likely a plugin conflict.
