### ISSUE TITLE
API question

### ISSUE THREAD

**Issue by LogGits** [rutgerkok/BlockLocker#51]
Is there a way to get the uuid of all players with access to a chest protection. I was looking at profile system via `findProtection() getAllowed()`. I'm just unsure how to get the uuid of the player from the profile as it only has a displayname and a saveObject. 
Any ideas?

**Comment by rutgerkok** [comment]
Not everything on the sign has an UUID, for example the line `[Everyone]` doesn't have an UUID. To get the UUID, check that the profile is an instance of [PlayerProfile](https://github.com/rutgerkok/BlockLocker/tree/f402e2a66e562868bef4d40d338108bab46d023f), cast it and then get the UUID.

**Comment by LogGits** [comment]
Ah ok cheers i was able to get it working using by doing that. Is there also an event for protection creation. E.g. BlockProtectEvent? Something like an event that can be cancelled to prevent the signs from being added. Loving the plugin, keep up the great work!

**Comment by rutgerkok** [comment]
Bit of a late reply, but currently there is no dedicated event. However, you can do `plugin.`[getLocationCheckers](https://github.com/rutgerkok/BlockLocker/blob/c15246b68a1616c9dc5defb2f8f46465c382b7ac/src/main/java/nl/rutgerkok/blocklocker/BlockLockerPlugin.java#L38)`().`[addChecker](https://github.com/rutgerkok/BlockLocker/blob/c15246b68a1616c9dc5defb2f8f46465c382b7ac/src/main/java/nl/rutgerkok/blocklocker/location/CombinedLocationChecker.java#L26)`(checker)`, where `checker` is an instance of a class that implements [LocationChecker](https://github.com/rutgerkok/BlockLocker/blob/c15246b68a1616c9dc5defb2f8f46465c382b7ac/src/main/java/nl/rutgerkok/blocklocker/location/LocationChecker.java). Would this be enough for you?

**Comment by LogGits** [comment]
Im setting up a thing that makes it so containers with specific properties are unprotectable. Something like a cancellable ProtectionCreateEvent would be useful for general purpose api hooks and for should also work for what i'm doing.

**Comment by rutgerkok** [comment]
I've added a basic event. Currently, it only reports the sign block and the player. Things I could add:

1. A list of blocks being protected (like the blocks of the chest or the blocks of the door)
2. A list of blocks that normally cannot be protected, but that also receive protection because of the blocks around them (like the block a door stands on or the block above a door where the sign is placed on)

Which of the two do you need? Or was the LocationChecker enough after all? (It does allow cancelling placement and looking up the protection location, after all.)

**Comment by LogGits** [comment]
@rutgerkok i'd need the block it's being connected to. e.g. a chest, furnace etc (instead of sign block).
